
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
tasks:
  - command: BACKENDURL=$(gp url 3000) npm run dev
  - init: npm ci

vscode:
  extensions:
    - vtrois.gitmoji-vscode
    - esbenp.prettier-vscode
    - octref.vetur
    - bradlc.vscode-tailwindcss
    - github.github-vscode-theme
    - eamodio.gitlens
