name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Run deployment webhook
        env:
          TOKEN: ${{ secrets.TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref }}
        run: |
          echo "Running webhook, see result below..."
          echo "Repo: $REPO"
          wget --content-on-error -q -O - "https://deploy.ejenda.org/" --method POST --header 'content-type: application/json' --body-data "{\"token\": \"$TOKEN\"}"

